Traceback (most recent call last):
  File "/home/jrladd/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# First create a parser object. It will work faster if you tell it not to collect IDs.
parser = etree.XMLParser(collect_ids=False)

# Parse your XML file into a "tree" object
tree = etree.parse('A50919.xml', parser)

# Get the XML from the tree object
paradiselost = tree.getroot()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m<ipython-input-2-a5fbe948cc49>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0;31m# Parse your XML file into a "tree" object[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0mtree[0m [0;34m=[0m [0metree[0m[0;34m.[0m[0mparse[0m[0;34m([0m[0;34m'A50919.xml'[0m[0;34m,[0m [0mparser[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0;34m[0m[0m
[1;32m      7[0m [0;31m# Get the XML from the tree object[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32msrc/lxml/etree.pyx[0m in [0;36mlxml.etree.parse[0;34m()[0m

[0;32msrc/lxml/parser.pxi[0m in [0;36mlxml.etree._parseDocument[0;34m()[0m

[0;32msrc/lxml/parser.pxi[0m in [0;36mlxml.etree._parseDocumentFromURL[0;34m()[0m

[0;32msrc/lxml/parser.pxi[0m in [0;36mlxml.etree._parseDocFromFile[0;34m()[0m

[0;32msrc/lxml/parser.pxi[0m in [0;36mlxml.etree._BaseParser._parseDocFromFile[0;34m()[0m

[0;32msrc/lxml/parser.pxi[0m in [0;36mlxml.etree._ParserContext._handleParseResultDoc[0;34m()[0m

[0;32msrc/lxml/parser.pxi[0m in [0;36mlxml.etree._handleParseResult[0;34m()[0m

[0;32msrc/lxml/parser.pxi[0m in [0;36mlxml.etree._raiseParseError[0;34m()[0m

[0;31mOSError[0m: Error reading file 'A50919.xml': failed to load external entity "A50919.xml"
OSError: Error reading file 'A50919.xml': failed to load external entity "A50919.xml"

